kind: Deployment
apiVersion: apps/v1
metadata:
  name: prativa-on-canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prativa-on-canvas
  template:
    metadata:
      labels:
        app: prativa-on-canvas
    spec:
      containers:
        - name: prativa-on-canvas
          image: java-springboot-image:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: prativa-on-canvas
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: prativa-on-canvas